### ISSUE TITLE
Addon breaks on sites without a page context

### ISSUE THREAD

**Issue by rrelmy** [flooris/statamic-hreflang#1]
As example on the 404 error page or a routed template the addon does not find an id and breaks the site

`ErrorException: Undefined index: id in C:\projects\awl\site\addons\HrefLang\HrefLangTags.php:17`

As a workaround I added this in the beginning of the tag
``` php
        if (empty($this->context['id'])) {
            return '';
        }
```

**Comment by fkwakkenbos** [comment]
@rrelmy Thanks!
I've added the fix into the repo.
